print("\t\t\t|-----------------------------------------------|")
print("\t\t\t|###############################################|")
print("\t\t\t|##################### RULES ###################|")
print("\t\t\t|\t\t THERE ARE TOTAL 10 QUESTION \t\t\t|")
print("\t\t\t|THERE ARE TOW LEVEL REGARD THESE 10 QUESTION\t|")
print("\t\t\t|###########QUESTION 1 --> 100 POINT############|")
print("\t\t\t|###########QUESTION 2 --> 150 POINT############|")
print("\t\t\t|###########QUESTION 3 --> 200 POINT############|")
print("\t\t\t|###########QUESTION 4 --> 250 POINT############|")
print("\t\t\t|###########QUESTION 5 --> 500 POINT############|")
print("\t\t\t|\t\t\tHERE YOU ENTER IN NEXT PART\t\t\t|")
print("\t\t\t|###########QUESTION 6 --> 600 POINT############|")
print("\t\t\t|###########QUESTION 7 --> 650 POINT############|")
print("\t\t\t|###########QUESTION 8 --> 750 POINT############|")
print("\t\t\t|###########QUESTION 9 --> 800 POINT############|")
print("\t\t\t|###########QUESTION 10 --> 1000 POINT##########|")
print("\t\t\t|###############################################|")
print("\t\t\t|-----------------------------------------------|")